is_train: True
ddp: False
stat: ts
training_speakers: [1]
root_path: ./
out_path: ./outputs/audio2pose/
cache_path: datasets/beat_cache/mhr_hand/
project: mhr_vqvae
data_path: ./data/
e_path: weights/AESKConv_240_100.bin
test_ckpt: weights/multi.bin
data_path_1: ./pretrained/
additional_data: False
dataset: beat_sep_lower
new_cache: True
ori_joints: beat_smplx_joints
tar_joints: beat_smplx_full
pose_rep: smplxflame_30
pose_norm: False
pose_fps: 30

vae_test_len: 64
vae_test_dim: 108
vae_test_stride: 20
vae_length: 256
vae_codebook_size: 256
vae_layer: 2
vae_grow: [1,1,2,1]
variational: False
vae_quantizer_lambda: 1.0

pose_dims: 108
pose_length: 64
stride: 20
facial_dims: 75
facial_rep: smplxflame_30
word_index_num: 11195
word_dims: 300
batch_size: 64
lr_base: 3e-4
decay_epochs: 9999
model: motion_representation
g_name: VQVAEConvZero
trainer: ae_mhr

rec_weight: 1
rec_pos_weight: 1
rec_ver_weight: 0
epochs: 500
test_period: 100
beat_align: False
port: 8692
